// <auto-generated />
using System;
using Customers.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Customers.Migrations
{
    [DbContext(typeof(customerDbContext))]
    [Migration("20200309160751_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Customers.Models.CustomerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Insert_Date");

                    b.Property<string>("Machine_IP");

                    b.Property<string>("Machine_Name");

                    b.Property<string>("Name");

                    b.Property<DateTime>("Update_Date");

                    b.Property<int>("User_ID");

                    b.Property<int>("User_ID_Update");

                    b.Property<string>("User_Name");

                    b.HasKey("Id");

                    b.ToTable("CustomersType");
                });
#pragma warning restore 612, 618
        }
    }
}
